dist: focal
language: minimal
os: linux
env:
  global:
    - PATH=$HOME/.volta:$HOME/.volta/bin:$PATH
before_install:
  - curl https://get.volta.sh | bash
  - volta install node@15.10.0
  - volta install pnpm@5.18.1
  - pnpm config set store-dir ~/.pnpm-store
install:
  - pnpm --recursive install
script:
  - pnpm --recursive --if-present --workspace-concurrency=1 run test
after_success:
  - pnpm --recursive run coverage
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
    - "$HOME/.volta"
